# Generated by Django 5.1.6 on 2025-02-20 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CHECKED_IN', 'Checked In'), ('IN_CIRCULATION', 'In Circulation'), ('BEING_REPAIRED', 'Being Repaired')], default='CHECKED_IN', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('media_type', models.CharField(choices=[('CD', 'CD'), ('VINYL', 'Vinyl'), ('BLU_RAY', 'Blu-ray'), ('CASSETTE', 'Cassette Tape')], default='OTHER', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('average_rating', models.FloatField(default=0.0)),
                ('collections', models.ManyToManyField(blank=True, related_name='items', to='music.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('google_account', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(default=None, height_field=100, upload_to='')),
                ('date_joined', models.DateTimeField(verbose_name='date_joined')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='librarian_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('google_account', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(default=None, height_field=100, upload_to='')),
                ('date_joined', models.DateTimeField(verbose_name='date_joined')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='patron_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.item')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.patron')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='private_users',
            field=models.ManyToManyField(blank=True, related_name='accessible_collections', to='music.patron'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='music.item')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='music.patron')),
            ],
            options={
                'unique_together': {('item', 'patron')},
            },
        ),
    ]
