# Generated by Django 5.1.6 on 2025-02-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="tags",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="patron",
            name="bio",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="patron",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
