# Generated by Django 4.2.19 on 2025-02-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AlterField(
            model_name='item',
            name='identifier',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
