# Generated by Django 5.1.6 on 2025-03-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_item_tags_patron_bio_patron_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="librarian",
            name="profile_picture",
            field=models.ImageField(default="default.jpg", upload_to="profile_picture"),
        ),
        migrations.AlterField(
            model_name="patron",
            name="profile_picture",
            field=models.ImageField(default="default.jpg", upload_to="profile_picture"),
        ),
    ]
