# Generated by Django 4.2.19 on 2025-02-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_item_id_alter_item_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='identifier',
        ),
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
