# Generated by Django 5.1.6 on 2025-02-18 17:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_item_identifier_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('google_account', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(height_field=100, upload_to='')),
                ('date_joined', models.DateTimeField(verbose_name='date_joined')),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('google_account', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(height_field=100, upload_to='')),
                ('date_joined', models.DateTimeField(verbose_name='date_joined')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='identifier',
            field=models.CharField(default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='media_type',
            field=models.CharField(choices=[('CD', 'CD'), ('VINYL', 'Vinyl'), ('BLU_RAY', 'Blu-ray'), ('CASSETTE', 'Cassette Tape')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('CHECKED_IN', 'Checked In'), ('IN_CIRCULATION', 'In Circulation'), ('BEING_REPAIRED', 'Being Repaired')], default='CHECKED_IN', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='items', to='music.collection'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.item')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.patron')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='private_users',
            field=models.ManyToManyField(blank=True, related_name='accessible_collections', to='music.patron'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='music.item')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='music.patron')),
            ],
            options={
                'unique_together': {('item', 'patron')},
            },
        ),
    ]
