# Generated by Django 4.2.19 on 2025-02-21 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_librarian_patron_item_average_rating_item_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='identifier',
        ),
    ]
