# Generated by Django 5.1.6 on 2025-02-20 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_collection_librarian_patron_item_average_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarian',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='patron',
            name='user_id',
        ),
        migrations.AddField(
            model_name='librarian',
            name='primary_key',
            field=models.AutoField(default=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='librarian',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='librarian_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patron',
            name='primary_key',
            field=models.AutoField(default=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patron',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='patron_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
