# Generated by Django 5.1.6 on 2025-02-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_remove_librarian_user_id_remove_patron_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='profile_picture',
            field=models.ImageField(default=None, height_field=100, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patron',
            name='profile_picture',
            field=models.ImageField(default=None, height_field=100, upload_to=''),
        ),
    ]
