# Generated by Django 5.1.6 on 2025-03-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0005_alter_librarian_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="librarian",
            name="profile_picture",
            field=models.ImageField(
                default="media/music/images/default.jpg", upload_to="profile_picture"
            ),
        ),
    ]
