# Generated by Django 5.1.6 on 2025-03-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0009_alter_librarian_profile_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="librarian",
            name="bio",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="librarian",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
