# Generated by Django 5.1.6 on 2025-03-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0010_librarian_bio_librarian_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="librarian",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="default.jpg", upload_to="profile_pics"
            ),
        ),
        migrations.AlterField(
            model_name="patron",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="default.jpg", upload_to="profile_pics"
            ),
        ),
    ]
