# Generated by Django 5.1.6 on 2025-03-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0011_alter_librarian_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="item_images"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="location",
            field=models.CharField(
                blank=True, default="Home Library", max_length=255, null=True
            ),
        ),
    ]
