# Generated by Django 5.1.6 on 2025-03-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0012_alter_item_image_alter_item_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="librarian",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="default.jpg", upload_to="profile-pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="patron",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="default.jpg", upload_to="profile-pictures/"
            ),
        ),
    ]
