# Generated by Django 5.1.6 on 2025-03-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0015_alter_librarian_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="librarian",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="default.jpg", upload_to="profile_pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="patron",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="default.jpg", upload_to="profile_pictures/"
            ),
        ),
    ]
