# Generated by Django 5.1.6 on 2025-03-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0017_alter_librarian_profile_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="image",
            field=models.ImageField(
                blank=True,
                default="collection_default.jpg",
                upload_to="collection_images",
            ),
        ),
        migrations.AlterField(
            model_name="librarian",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="default.jpg", upload_to="profile_pics"
            ),
        ),
        migrations.AlterField(
            model_name="patron",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="default.jpg", upload_to="profile_pics"
            ),
        ),
    ]
