# Generated by Django 5.1.6 on 2025-03-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0018_collection_image_alter_librarian_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="collection_images"
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="item_images"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
