# Generated by Django 5.1.6 on 2025-03-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0019_alter_collection_description_alter_collection_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
