# Generated by Django 5.1.6 on 2025-03-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0019_alter_collection_description_alter_collection_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patron",
            name="saved_items",
            field=models.ManyToManyField(
                blank=True, related_name="saved_items", to="music.item"
            ),
        ),
    ]
