# Generated by Django 5.1.6 on 2025-03-28 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_alter_librarian_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='music.librarian'),
            preserve_default=False,
        ),
    ]
