# Generated by Django 5.1.6 on 2025-03-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0022_alter_librarian_profile_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="pending_users",
            field=models.ManyToManyField(
                blank=True, related_name="pending_collections", to="music.patron"
            ),
        ),
    ]
