# Generated by Django 5.1.6 on 2025-03-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0023_collection_pending_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="thumbs_up",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="requested_by",
            field=models.ManyToManyField(
                blank=True, related_name="requested_by", to="music.patron"
            ),
        ),
        migrations.AddField(
            model_name="patron",
            name="borrowed_items",
            field=models.ManyToManyField(
                blank=True, related_name="borrowed_items", to="music.item"
            ),
        ),
        migrations.AddField(
            model_name="patron",
            name="comments_by",
            field=models.ManyToManyField(
                blank=True, related_name="comments_by", to="music.comment"
            ),
        ),
        migrations.AddField(
            model_name="patron",
            name="ratings_by",
            field=models.ManyToManyField(
                blank=True, related_name="ratings_by", to="music.rating"
            ),
        ),
    ]
