# Generated by Django 5.1.6 on 2025-03-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0024_comment_thumbs_up_item_due_date_item_requested_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="collections",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="items", to="music.collection"
            ),
        ),
    ]
