# Generated by Django 5.1.6 on 2025-03-27 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0025_alter_item_collections"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator",
                to="music.patron",
            ),
        ),
    ]
