# Generated by Django 5.1.6 on 2025-03-27 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0026_collection_creator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="image",
        ),
    ]
