# Generated by Django 5.1.6 on 2025-03-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0027_remove_collection_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
