# Generated by Django 5.1.6 on 2025-03-27 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0028_collection_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="slug",
        ),
    ]
