# Generated by Django 5.1.6 on 2025-03-28 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_alter_item_owner'),
        ('music', '0029_remove_collection_slug'),
    ]

    operations = [
    ]
