# Generated by Django 5.1.6 on 2025-03-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0030_merge_20250328_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='items', to='music.collection'),
        ),
    ]
