# Generated by Django 5.1.6 on 2025-03-28 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0032_alter_item_requested_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='requested_by',
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_of_item', to=settings.AUTH_USER_MODEL)),
                ('requested_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requested_item', to='music.item')),
                ('requester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'requester')},
            },
        ),
    ]
