# Generated by Django 5.1.6 on 2025-03-28 04:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0033_remove_item_requested_by_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='BorrowRequest',
        ),
    ]
