# Generated by Django 5.1.6 on 2025-03-28 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0034_rename_request_borrowrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='borrowrequest',
        #     name='owner',
        # ),
        migrations.AddField(
            model_name='borrowrequest',
            name='item_owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='borrowrequest',
            unique_together={('item_owner', 'requester')},
        ),
    ]
