# Generated by Django 5.1.6 on 2025-03-28 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0035_alter_borrowrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrequest',
            name='owner',
        ),
    ]
