# Generated by Django 5.1.6 on 2025-03-28 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0036_remove_borrowrequest_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='item_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='requested_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_item', to='music.item'),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL),
        ),
    ]
