# Generated by Django 5.1.6 on 2025-03-29 03:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0037_alter_borrowrequest_item_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrowrequest',
            unique_together={('item_owner', 'requester', 'requested_item')},
        ),
    ]
