# Generated by Django 5.1.6 on 2025-03-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0038_alter_borrowrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('DENIED', 'Denied')], default='PENDING', max_length=20),
        ),
    ]
