# Generated by Django 5.1.6 on 2025-03-29 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0039_borrowrequest_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="borrowrequest",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="borrowrequest",
            name="requesters",
            field=models.ManyToManyField(
                blank=True, related_name="requesters", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name="borrowrequest",
            name="requester",
        ),
    ]
