# Generated by Django 5.1.6 on 2025-03-30 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0040_alter_borrowrequest_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrequest',
            name='status',
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('CHECKED_IN', 'Checked In'), ('IN_CIRCULATION', 'In Circulation'), ('BEING_REPAIRED', 'Being Repaired'), ('BORROWED', 'Borrowed')], default='CHECKED_IN', max_length=20),
        ),
        migrations.CreateModel(
            name='BorrowRequester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('DENIED', 'Denied')], default='PENDING', max_length=20)),
                ('associated_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_request', to='music.borrowrequest')),
                ('request_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='requesters',
            field=models.ManyToManyField(blank=True, related_name='requesters', to='music.borrowrequester'),
        ),
    ]
