# Generated by Django 5.1.6 on 2025-04-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0042_alter_borrowrequester_request_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="librarian",
            name="saved_items",
            field=models.ManyToManyField(
                blank=True, related_name="librarian_saved_items", to="music.item"
            ),
        ),
        migrations.AlterField(
            model_name="patron",
            name="saved_items",
            field=models.ManyToManyField(
                blank=True, related_name="patron_saved_items", to="music.item"
            ),
        ),
    ]
