# Generated by Django 5.1.6 on 2025-04-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0043_librarian_saved_items_alter_patron_saved_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="genre",
            field=models.TextField(blank=True, null=True),
        ),
    ]
