# Generated by Django 5.1.6 on 2025-04-12 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0043_librarian_saved_items_alter_patron_saved_items"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowrequest",
            name="requesters",
        ),
        migrations.RemoveField(
            model_name="borrowrequest",
            name="item_owner",
        ),
        migrations.AddField(
            model_name="borrowrequest",
            name="requester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requester",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="borrowrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("DENIED", "Denied"),
                    ("OVERDUE", "Overdue"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="BorrowRequester",
        ),
    ]
