# Generated by Django 5.1.6 on 2025-04-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0044_remove_borrowrequest_requesters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20),
        ),
    ]
