# Generated by Django 5.1.6 on 2025-04-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0044_item_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='genre',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
