# Generated by Django 5.1.6 on 2025-04-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0045_alter_borrowrequest_status"),
        ("music", "0046_alter_item_genre"),
    ]

    operations = []
