# Generated by Django 5.1.6 on 2025-04-13 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0047_merge_20250412_1046"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="owner",
        ),
    ]
