# Generated by Django 5.1.6 on 2025-04-12 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0048_remove_item_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 12, 15, 6, 30, 741478, tzinfo=datetime.timezone.utc)),
        ),
    ]
