# Generated by Django 5.1.6 on 2025-04-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0048_remove_item_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("CHECKED_IN", "Checked In"),
                    ("IN_CIRCULATION", "In Circulation"),
                    ("BEING_REPAIRED", "Being Repaired"),
                ],
                default="CHECKED_IN",
                max_length=20,
            ),
        ),
    ]
