# Generated by Django 5.1.6 on 2025-04-12 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0049_alter_item_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 12, 15, 7, 9, 360984, tzinfo=datetime.timezone.utc)),
        ),
    ]
