# Generated by Django 5.1.6 on 2025-04-12 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0050_alter_item_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 4, 12)),
        ),
    ]
