# Generated by Django 5.1.6 on 2025-04-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0051_alter_item_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
