# Generated by Django 5.1.6 on 2025-04-13 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0049_alter_item_status"),
        ("music", "0054_alter_item_due_date"),
    ]

    operations = []
