# Generated by Django 5.1.6 on 2025-04-22 15:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0055_merge_0049_alter_item_status_0054_alter_item_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unique_str',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
