# Generated by Django 5.1.6 on 2025-04-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0055_merge_0049_alter_item_status_0054_alter_item_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
