# Generated by Django 5.1.6 on 2025-04-22 15:36

import uuid
from django.db import migrations


def gen_uuid(apps, schema_editor):
    Item = apps.get_model("music", "Item")
    for row in Item.objects.all():
        row.unique_str = uuid.uuid4()
        row.save(update_fields=["unique_str"])

class Migration(migrations.Migration):

    dependencies = [
        ('music', '0056_item_unique_str'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
