# Generated by Django 5.1.6 on 2025-04-22 15:36
import uuid
from django.db import migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0057_auto_20250422_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unique_str',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
