# Generated by Django 5.1.6 on 2025-04-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0058_auto_20250422_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='unique_str',
            new_name='serial_num',
        ),
    ]
