# Generated by Django 5.1.6 on 2025-04-27 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0056_alter_item_average_rating'),
        ('music', '0059_rename_unique_str_item_serial_num'),
    ]

    operations = [
    ]
