# Generated by Django 5.1.6 on 2025-04-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0061_alter_comment_text_alter_item_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='audio',
            field=models.FileField(blank=True, default=None, null=True, upload_to='item_audio'),
        ),
    ]
