name: Run Music App Tests

on:
    pull_request:
        branches: [tests-for-actions]
    workflow_call:

jobs:

    test: 
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v3
              with: 
                python-version: 3.12.1
            - run: python -m pip install --upgrade pip; pip install -r requirements.txt
            - run: python manage.py test
              env:
                AWS_KEY: ${{ secrets.AWS_KEY }}
                AWS_ID: ${{ secrets.AWS_ID }}
                BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        